# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stickyhand < Formula
  desc "✋ Fetch webpage content into structured text using crawlers or AI as your want."
  homepage "https://github.com/RealAlexandreAI/sticky-hand"
  version "0.0.3"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.3/stickyhand_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "49a7ec397313946a189debb60551080ab886ea4230cfcc41863f893e8f811350"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.3/stickyhand_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3b86031e8fdaf668f83cc46555811660e090338a16ec9be13499eb1da4ea84a2"

      def install
        bin.install "stickyhand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.3/stickyhand_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "85c5d24edd0bf0ad495831674fc7ad1d2c6a627fb4dac27d08f7681162a96630"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.3/stickyhand_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "59ce4417f81835fce1f57b9525ffc247c9c5ca2122a4a09bb676317879be673b"

      def install
        bin.install "stickyhand"
      end
    end
  end

  test do
    system "#{bin}/stickyhand -v"
  end
end
