# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stickyhand < Formula
  desc "✋ Fetch webpage content into structured text using crawlers or AI as your want."
  homepage "https://github.com/RealAlexandreAI/sticky-hand"
  version "0.0.6"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.6/stickyhand_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8bd44dff20314933633c55c906c5c367741209b2c92b950103d654c115cc347f"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.6/stickyhand_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "47bcaf2b39cff336292cd770b6eeb58f7b2bead32b7105dca1fe24e6447511ea"

      def install
        bin.install "stickyhand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.6/stickyhand_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "8a5cc9355f3aad991f9757cc759c3a6a0d55e60f8a2d18c24696a10654957da9"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.6/stickyhand_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "75162ecef1169e48bfaa3da6f1eeaa407f477da9dc3adde7b97fb00b6c765ffb"

      def install
        bin.install "stickyhand"
      end
    end
  end

  test do
    system "#{bin}/stickyhand -v"
  end
end
