# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stickyhand < Formula
  desc "✋ Fetch webpage content into structured text using crawlers or AI as your want."
  homepage "https://github.com/RealAlexandreAI/sticky-hand"
  version "0.0.4"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.4/stickyhand_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9d5fc3e1c4354d87fa56d2314df740b7f582cf34f442375e2bba2866ec5846bb"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.4/stickyhand_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fd2568657b0600a4a3e1894237d162ed3b1a9f9601f1b8ed8e116e2f7c2ac641"

      def install
        bin.install "stickyhand"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.4/stickyhand_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "7ae6744a3c270e538ddc575f1d861963c625e711e9e7f743fd6a512051c889af"

      def install
        bin.install "stickyhand"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RealAlexandreAI/sticky-hand/releases/download/v0.0.4/stickyhand_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f479eb353d50bf7b8e477a4f3c2aa8cd1f48b0b59116271288ecfde29b8358f9"

      def install
        bin.install "stickyhand"
      end
    end
  end

  test do
    system "#{bin}/stickyhand -v"
  end
end
